export default [
  {
    key: 'living-home',
    title: '내 정보',
    description: '계좌·알림·이동점포로 이동합니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>내 계좌</span><i>✓</i></div><div class="choice "><span>납부 알림</span><i></i></div></div><div class="choices"><div class="choice active"><span>이동점포 정보</span><i>✓</i></div><div class="choice "><span>가입 정보</span><i></i></div></div>',
    primaryLabel: '',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: true,
  },
  {
    key: 'living-accounts',
    title: '계좌 목록',
    description: '잔액·사용 가능 금액·출금 계좌를 봅니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>신한은행 · 1234</strong><p>잔액 1,240,000원</p></div></section><div class="meta"><span>사용 가능</span><strong>1,180,000원</strong></div><div class="choices"><div class="choice active"><span>출금 계좌로 선택</span><i>✓</i></div><div class="choice "><span>다른 계좌 보기</span><i></i></div></div>',
    primaryLabel: '선택 완료',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-accounts-empty',
    title: '연결 계좌 없음',
    description: '등록된 계좌가 없을 때의 빈 상태입니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>연결된 계좌가 없어요</strong><p>계좌를 등록하면 잔액과 출금 계좌를 확인할 수 있습니다.</p></div></section>',
    primaryLabel: '계좌 등록',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-accounts-error',
    title: '계좌 조회 실패',
    description: '일시적인 조회 오류만 안내합니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>계좌 정보를 불러오지 못했어요</strong><p>잠시 후 다시 시도해 주세요.</p></div></section><div class="note"><b>안내</b><span>명세에 없는 고객센터 전화 버튼은 제외했습니다.</span></div>',
    primaryLabel: '다시 시도',
    secondaryLabel: '',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-session-expired',
    title: '세션 만료',
    description: '인증이 만료되면 재로그인을 요청합니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">?</div><div><strong>안전한 이용을 위해 다시 확인해 주세요</strong><p>로그인 시간이 만료되었습니다.</p></div></section>',
    primaryLabel: '다시 로그인',
    secondaryLabel: '',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminders',
    title: '납부 알림 목록',
    description: '예정된 알림과 상태를 확인합니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>9월 10일 · 전기요금</span><i>✓</i></div><div class="choice "><span>9월 15일 · 통신요금</span><i></i></div></div>',
    primaryLabel: '새 알림 만들기',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminder-create',
    title: '알림 만들기',
    description: '대상·날짜·시간을 설정합니다.',
    contentHtml:
      '<div class="field "><span>알림 이름</span><b>›</b></div><div class="field "><span>날짜 선택</span><b>›</b></div><div class="field "><span>시간 선택</span><b>›</b></div>',
    primaryLabel: '알림 저장',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminder-edit',
    title: '알림 편집·취소',
    description: '저장한 알림을 수정하거나 취소합니다.',
    contentHtml:
      '<div class="field focus"><span>전기요금 납부일</span><b>›</b></div><div class="field "><span>2026.09.10 · 오전 9:00</span><b>›</b></div>',
    primaryLabel: '변경 저장',
    secondaryLabel: '알림 취소',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminder-arrived',
    title: '알림 도착',
    description: '내용 확인 중심의 알림으로 정리합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>오늘은 전기요금 납부일이에요</strong><p>등록해 둔 일정을 확인해 주세요.</p></div></section><div class="note"><b>안내</b><span>즉시 납부와 “내일 다시 알림” 버튼은 제외했습니다.</span></div>',
    primaryLabel: '알림 상세 보기',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-branches',
    title: '이동점포 목록',
    description: '갱신 시각과 운영 정보를 함께 표시합니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>은빛 이동점포 · 1.2km</span><i>✓</i></div><div class="choice "><span>행복 이동점포 · 3.8km</span><i></i></div></div><div class="meta"><span>정보 갱신</span><strong>2026.09.02 09:00</strong></div>',
    primaryLabel: '상세 보기',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-branch-detail',
    title: '이동점포 상세',
    description: '업무와 준비물 중심으로 제공합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>은빛 이동점포</strong><p>오늘 10:00–15:00</p></div></section><div class="choices"><div class="choice active"><span>가능 업무</span><i>✓</i></div><div class="choice "><span>신분증 등 준비물</span><i></i></div></div><div class="note"><b>안내</b><span>명세에 없는 전화·길찾기 버튼은 제외했습니다.</span></div>',
    primaryLabel: '목록으로',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-location-permission',
    title: '위치 권한 없음',
    description: '지역 직접 선택으로 서비스를 계속 이용합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>현재 위치를 확인할 수 없어요</strong><p>지역을 직접 선택해 이동점포를 찾을 수 있습니다.</p></div></section><div class="field "><span>시·군·구 선택</span><b>›</b></div>',
    primaryLabel: '이 지역에서 찾기',
    secondaryLabel: '설정 열기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-voice-settings',
    title: '내 목소리 설정',
    description: '음성 안내를 내게 맞춥니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>낮은 남성 목소리</span><i>✓</i></div><div class="choice "><span>여성 목소리</span><i></i></div></div><div class="field"><span>말하기 속도</span><b>조금 느리게</b></div><div class="field"><span>글씨 크기</span><b>크게</b></div>',
    primaryLabel: '미리 들어보기',
    secondaryLabel: '저장하기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-profile-edit',
    title: '내 정보 고치기',
    description: '이름과 연락처를 바꿉니다.',
    contentHtml:
      '<div class="field"><span>이름</span><b>김순자</b></div><div class="field focus"><span>휴대전화</span><b>010-0000-0000</b></div><div class="field"><span>주소</span><b>서울 성동구</b></div>',
    primaryLabel: '저장하기',
    secondaryLabel: '취소',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-emergency-contact-edit',
    title: '비상 연락처 고치기',
    description: '믿을 수 있는 분을 바꿉니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>지금 등록된 분</strong><p>김영희 · 자녀 · 010-1234-5678</p></div></section><div class="field focus"><span>새 연락처</span><i style="font-style:normal">›</i></div><div class="note"><b>안내</b><span>이상한 송금이 있을 때 이분께 먼저 알려요.</span></div>',
    primaryLabel: '바꾸기',
    secondaryLabel: '그대로 두기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-consents',
    title: '동의 다시 보기',
    description: '동의한 항목을 바꿀 수 있습니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>마이데이터</span><i>✓</i></div><div class="choice active"><span>AI 음성정보</span><i>✓</i></div></div><div class="choices"><div class="choice "><span>국외 이전</span><i></i></div><div class="choice "><span>마케팅 알림</span><i></i></div></div><div class="note"><b>안내</b><span>언제든 끄셔도 기본 기능은 그대로예요.</span></div>',
    primaryLabel: '바꾼 대로 저장',
    secondaryLabel: '취소',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminders-empty',
    title: '알림이 없어요',
    description: '아직 받은 알림이 없습니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>새로운 알림이 없어요</strong><p>납부일이 다가오면 알려드릴게요.</p></div></section><div class="note"><b>안내</b><span>알림을 켜두시면 놓치는 일이 줄어요.</span></div>',
    primaryLabel: '알림 만들기',
    secondaryLabel: '홈으로',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminders-error',
    title: '알림을 못 가져왔어요',
    description: '목록을 불러오지 못했습니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>잠시 연결이 안 돼요</strong><p>통신 상태를 확인해 주세요.</p></div></section>',
    primaryLabel: '다시 불러오기',
    secondaryLabel: '홈으로',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminders-disabled',
    title: '알림이 꺼져 있어요',
    description: '알림 권한이 없습니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">!</div><div><strong>알림을 보낼 수 없어요</strong><p>납부일을 못 알려드려요.</p></div></section><div class="note"><b>안내</b><span>설정 › 귀편한 금융 › 알림에서 켜실 수 있어요.</span></div>',
    primaryLabel: '설정 열기',
    secondaryLabel: '괜찮아요',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-branches-empty',
    title: '가까운 곳이 없어요',
    description: '주변에 이동점포가 없습니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">!</div><div><strong>10km 안에 없어요</strong><p>다른 지역으로 넓혀서 찾아볼까요?</p></div></section><div class="field focus"><span>찾는 지역</span><b>성동구</b></div>',
    primaryLabel: '넓혀서 찾기',
    secondaryLabel: '전화로 묻기',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-branches-error',
    title: '못 찾아봤어요',
    description: '이동점포 정보를 불러오지 못했습니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>잠시 연결이 안 돼요</strong><p>통신 상태를 확인해 주세요.</p></div></section>',
    primaryLabel: '다시 찾기',
    secondaryLabel: '전화로 묻기',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminder-speak',
    title: '소리로 알려드릴까요',
    description: '알림을 소리로 들을지 직접 정합니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>소리로 알려주기</span><i>✓</i></div><div class="choice "><span>진동만</span><i></i></div></div><div class="field"><span>알림 목소리</span><b>낮은 남성</b></div><div class="field"><span>미리 알려주기</span><b>3일 전부터</b></div><div class="note"><b>안내</b><span>알림이 올 땐 진동으로만 알려요. 내용은 화면을 열었을 때 읽어드려요.</span></div>',
    primaryLabel: '미리 들어보기',
    secondaryLabel: '저장하기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminder-notice',
    title: '알려드릴 것이 있어요',
    description: '소리 없이 진동으로 먼저 알립니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>전기요금 납부일이 3일 남았어요</strong><p>눌러서 들으시면 자세히 알려드려요.</p></div></section><div class="meta"><span>알림 온 시각</span><b>방금</b></div><div class="note"><b>안내</b><span>밖에서도 안심하시라고, 금액은 소리로 먼저 말하지 않아요.</span></div>',
    primaryLabel: '들어보기',
    secondaryLabel: '나중에',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminder-reading',
    title: '읽어드리는 중',
    description: '알림 내용을 소리로 안내합니다.',
    contentHtml:
      '<div class="voice"><span class="glow g1"></span><span class="glow g2"></span><div class="mic-wrap"><span class="pulse p1"></span><span class="pulse p2"></span><span class="mic"><span class="mic-body"></span><span class="mic-stem"></span></span></div><div class="wave"><i style="height:12px"></i><i style="height:20px"></i><i style="height:32px"></i><i style="height:46px"></i><i style="height:28px"></i><i style="height:54px"></i><i style="height:64px"></i><i style="height:42px"></i><i style="height:58px"></i><i style="height:36px"></i><i style="height:50px"></i><i style="height:24px"></i><i style="height:38px"></i><i style="height:18px"></i><i style="height:12px"></i></div><p class="vstat"><span class="live"></span>읽어드리는 중</p></div><div class="stt done"><div class="stt-head"><span class="stt-dot"></span>읽고 있는 내용</div><p class="stt-text">전기요금 사만 팔천이백 원, 이달 스무닷새까지</p></div><div class="meta"><span>숫자로 다시</span><b>사 · 팔 · 이 · 공 · 공</b></div>',
    primaryLabel: '다시 듣기',
    secondaryLabel: '그만 듣기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminder-quiet-hours',
    title: '밤에는 조용히',
    description: '정한 시간에는 소리 없이 진동만 옵니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>조용한 시간 켜기</span><i>✓</i></div><div class="choice "><span>끄기</span><i></i></div></div><div class="field"><span>시작</span><b>밤 9시</b></div><div class="field"><span>끝</span><b>아침 7시</b></div><div class="note"><b>안내</b><span>급한 알림은 이 시간에도 진동으로 알려드려요.</span></div>',
    primaryLabel: '저장하기',
    secondaryLabel: '취소',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'living-reminder-missed',
    title: '못 들으신 알림',
    description: '아직 확인하지 않은 알림을 모아 보여줍니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>세 건이 기다리고 있어요</strong><p>하나씩 차례로 읽어드릴게요.</p></div></section><div class="meta"><span>전기요금 납부일</span><b>3일 전</b></div><div class="meta"><span>가스요금 납부일</span><b>어제</b></div><div class="meta"><span>송금 완료</span><b>오늘 오전</b></div>',
    primaryLabel: '모두 들어보기',
    secondaryLabel: '목록만 보기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
]
