module.exports = {
  extends: ['@commitlint/config-conventional'],
  parserPreset: {
    parserOpts: {
      headerPattern: /^(?<type>.+):\s+(?<subject>.+)$/,
      headerCorrespondence: ['type', 'subject'],
    },
  },
  rules: {
    'subject-case': [0],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [0],
    'type-empty': [2, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'Feat',
        'Fix',
        'Docs',
        'Refactor',
        'Style',
        'Test',
        'Chore',
        'Remove',
        '✨ Feat',
        ':sparkles: Feat',
        '🐛 Fix',
        ':bug: Fix',
        '📝 Docs',
        ':memo: Docs',
        '♻ Refactor',
        '♻️ Refactor',
        ':recycle: Refactor',
        '🎨 Style',
        ':art: Style',
        '🧪 Test',
        ':test_tube: Test',
        '📦 Chore',
        ':package: Chore',
        '🔥 Remove',
        ':fire: Remove',
      ],
    ],
  },
}
