export default [
  {
    id: '3-01',
    number: '3-01',
    title: '고지서 목록',
    description: '등록된 고지서 상태와 납부기한을 봅니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>전기요금 · 48,200원</span><i>✓</i></div><div class="choice "><span>통신요금 · 납부 완료</span><i></i></div></div>',
    primaryLabel: '고지서 등록',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: true,
  },
  {
    id: '3-02',
    number: '3-02',
    title: '촬영 또는 앨범에서 선택',
    description: '카메라와 앨범 중 하나를 선택합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>고지서를 화면 안에 맞춰 주세요</strong><p>빛 반사를 피하면 더 정확해요.</p></div></section><div class="choices"><div class="choice active"><span>카메라 촬영</span><i>✓</i></div><div class="choice "><span>앨범에서 선택</span><i></i></div></div><div class="note"><b>안내</b><span>명세에 없는 플래시 토글은 제외했습니다.</span></div>',
    primaryLabel: '촬영',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-02A',
    number: '3-02A',
    title: '고지서를 비춰 주세요',
    description: '네 모서리가 모두 보이게 맞춰 주세요.',
    contentHtml:
      '<div class="viewfinder"><div class="vf-doc"></div><div class="vf-corner tl"></div><div class="vf-corner tr"></div><div class="vf-corner bl"></div><div class="vf-corner br"></div><div class="vf-hint">테두리가 초록색이 되면 찍어 주세요</div></div><div class="note"><b>안내</b><span>빛 반사를 피하면 더 정확해요.</span></div>',
    primaryLabel: '촬영',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-03',
    number: '3-03',
    title: '업로드·OCR 처리',
    description: '문서를 업로드하고 항목을 인식합니다.',
    contentHtml:
      '<div class="steps"><i class="on"></i><i class="on"></i><i class=""></i><i class=""></i></div><section class="hero "><div class="hero-icon">✓</div><div><strong>고지서를 읽고 있어요</strong><p>금액과 납부기관을 확인합니다.</p></div></section>',
    primaryLabel: '',
    secondaryLabel: '취소',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-04',
    number: '3-04',
    title: '인식 결과 확인',
    description: '추출된 필드를 납부 전에 검토합니다.',
    contentHtml:
      '<div class="meta"><span>기관</span><strong>한국전력</strong></div><div class="meta"><span>납부 금액</span><strong>48,200원</strong></div><div class="meta"><span>납부 기한</span><strong>2026.09.10</strong></div>',
    primaryLabel: '내용 확인',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-05',
    number: '3-05',
    title: '낮은 신뢰도 수정',
    description: '확실하지 않은 필드만 직접 수정합니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">?</div><div><strong>금액을 다시 확인해 주세요</strong><p>인식 정확도가 낮은 항목입니다.</p></div></section><div class="field focus"><span>48,200원</span><b>›</b></div><div class="note"><b>안내</b><span>전체 양식을 다시 입력하게 하지 않습니다.</span></div>',
    primaryLabel: '수정 완료',
    secondaryLabel: '',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-06',
    number: '3-06',
    title: '납부 최종 확인',
    description: '출금 계좌와 납부 내용을 확인합니다.',
    contentHtml:
      '<div class="meta"><span>납부처</span><strong>한국전력</strong></div><div class="meta"><span>금액</span><strong>48,200원</strong></div><div class="meta"><span>출금 계좌</span><strong>신한 · 1234</strong></div>',
    primaryLabel: '납부하기',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-07',
    number: '3-07',
    title: '납부 완료',
    description: '결제 식별자와 상태만 제공합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>납부가 완료됐어요</strong><p>한국전력 48,200원</p></div></section><div class="meta"><span>결제 번호</span><strong>PAY-260902-41</strong></div><div class="meta"><span>처리 시각</span><strong>오후 3:12</strong></div><div class="note"><b>안내</b><span>영수증 보기와 즉시 잔액은 제외했습니다.</span></div>',
    primaryLabel: '확인',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-08',
    number: '3-08',
    title: '인식 실패',
    description: '재촬영 또는 파일 재선택을 안내합니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>내용을 읽지 못했어요</strong><p>흐림과 잘림이 없는지 확인해 주세요.</p></div></section>',
    primaryLabel: '다시 촬영',
    secondaryLabel: '다른 파일 선택',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-09',
    number: '3-09',
    title: '지원하지 않는 파일',
    description: '파일 형식과 크기 오류를 구분합니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>파일을 올릴 수 없어요</strong><p>지원 형식 또는 최대 용량을 확인해 주세요.</p></div></section><div class="choices"><div class="choice active"><span>JPG · PNG · PDF</span><i>✓</i></div><div class="choice "><span>허용 용량 안내</span><i></i></div></div>',
    primaryLabel: '다른 파일 선택',
    secondaryLabel: '',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-10',
    number: '3-10',
    title: '카메라 권한 없음',
    description: '거부 시 파일 선택 경로를 제공합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>카메라 권한이 필요해요</strong><p>촬영할 때만 권한을 요청합니다.</p></div></section>',
    primaryLabel: '설정 열기',
    secondaryLabel: '파일에서 선택',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-11',
    number: '3-11',
    title: '확인 정보 만료',
    description: '오래된 확인 정보는 다시 검토합니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">?</div><div><strong>확인 시간이 지났어요</strong><p>최신 납부 정보를 다시 불러옵니다.</p></div></section>',
    primaryLabel: '다시 확인',
    secondaryLabel: '',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-12',
    number: '3-12',
    title: '사용자 취소',
    description: '취소한 촬영 결과를 목록에 남기지 않습니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>등록을 취소했어요</strong><p>아직 저장되거나 납부된 내용은 없습니다.</p></div></section>',
    primaryLabel: '고지서 목록으로',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-13',
    number: '3-13',
    title: '중복 요청 처리',
    description: '같은 납부 요청은 최초 결과를 재사용합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>이미 처리된 요청이에요</strong><p>처음 완료된 결과를 안전하게 보여드립니다.</p></div></section><div class="meta"><span>상태</span><strong>완료</strong></div><div class="meta"><span>결제 번호</span><strong>PAY-260902-41</strong></div>',
    primaryLabel: '결과 확인',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-14',
    number: '3-14',
    title: '납부번호 확인',
    description: '읽어낸 납부번호를 확인합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>납부번호를 읽었어요</strong><p>숫자가 맞는지 봐주세요.</p></div></section><div class="field focus"><span>납부번호</span><b>0123-4567-89</b></div><div class="note"><b>안내</b><span>한 자리만 달라도 다른 곳으로 가요.</span></div>',
    primaryLabel: '맞아요',
    secondaryLabel: '고칠게요',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-15',
    number: '3-15',
    title: '읽은 정확도',
    description: '항목마다 얼마나 확실한지 보여드립니다.',
    contentHtml:
      '<div class="meta"><span>납부번호</span><b>확실해요</b></div><div class="meta"><span>금액</span><b>확실해요</b></div><div class="meta"><span>납부기한</span><b>조금 흐려요</b></div><div class="note"><b>안내</b><span>흐린 항목만 확인해 주시면 돼요.</span></div>',
    primaryLabel: '흐린 곳 고치기',
    secondaryLabel: '이대로 진행',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-16',
    number: '3-16',
    title: '읽어드릴게요',
    description: '고지서 내용을 소리로 확인합니다.',
    contentHtml:
      '<div class="voice"><span class="glow g1"></span><span class="glow g2"></span><div class="mic-wrap"><span class="pulse p1"></span><span class="pulse p2"></span><span class="mic"><span class="mic-body"></span><span class="mic-stem"></span></span></div><div class="wave"><i style="height:12px"></i><i style="height:20px"></i><i style="height:32px"></i><i style="height:46px"></i><i style="height:28px"></i><i style="height:54px"></i><i style="height:64px"></i><i style="height:42px"></i><i style="height:58px"></i><i style="height:36px"></i><i style="height:50px"></i><i style="height:24px"></i><i style="height:38px"></i><i style="height:18px"></i><i style="height:12px"></i></div><p class="vstat"><span class="live"></span>읽어드리는 중</p></div><div class="stt done"><div class="stt-head"><span class="stt-dot"></span>읽고 있는 내용</div><p class="stt-text">전기요금 48,200원, 이달 25일까지</p></div>',
    primaryLabel: '다시 듣기',
    secondaryLabel: '음성 끄기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-17',
    number: '3-17',
    title: '다시 찍어볼까요',
    description: '더 또렷하게 다시 촬영합니다.',
    contentHtml:
      '<div class="viewfinder"><div class="vf-doc"></div><div class="vf-corner tl"></div><div class="vf-corner tr"></div><div class="vf-corner bl"></div><div class="vf-corner br"></div><div class="vf-hint">글자가 흐리면 조금 더 가까이</div></div><div class="note"><b>안내</b><span>빛 반사만 피하면 훨씬 잘 읽혀요.</span></div>',
    primaryLabel: '다시 촬영',
    secondaryLabel: '직접 입력하기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-18',
    number: '3-18',
    title: '못 읽는 형식이에요',
    description: '지원하지 않는 파일입니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>이 파일은 열 수 없어요</strong><p>사진(JPG·PNG)이나 PDF만 됩니다.</p></div></section><div class="meta"><span>고른 파일</span><b>bill.hwp</b></div>',
    primaryLabel: '다른 파일 고르기',
    secondaryLabel: '촬영하기',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-19',
    number: '3-19',
    title: '파일이 너무 커요',
    description: '크기 제한을 넘었습니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>20MB까지만 올릴 수 있어요</strong><p>이 파일은 34MB예요.</p></div></section><div class="note"><b>안내</b><span>직접 찍으시면 크기가 알맞게 맞춰져요.</span></div>',
    primaryLabel: '촬영하기',
    secondaryLabel: '다른 파일 고르기',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-20',
    number: '3-20',
    title: '지난 고지서',
    description: '저장해 둔 고지서를 봅니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>전기요금 · 5월분</strong><p>이미 납부를 마친 고지서예요.</p></div></section><div class="meta"><span>납부한 금액</span><b>48,200원</b></div><div class="meta"><span>납부한 날</span><b>5월 24일</b></div><div class="meta"><span>납부번호</span><b>0123-4567-89</b></div>',
    primaryLabel: '영수증 보기',
    secondaryLabel: '목록으로',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-21',
    number: '3-21',
    title: '납부하는 중',
    description: '지금 납부를 처리하고 있습니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>은행에 보내고 있어요</strong><p>잠시만 기다려 주세요.</p></div></section><div class="steps"><i class="on"></i><i class="on"></i><i class=""></i></div><div class="amount"><small>납부 금액</small><strong>48,200원</strong></div>',
    primaryLabel: '',
    secondaryLabel: '기다리는 중…',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    id: '3-22',
    number: '3-22',
    title: '납부하지 못했어요',
    description: '서버에서 처리하지 못했습니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>잠시 문제가 생겼어요</strong><p>돈은 빠져나가지 않았어요.</p></div></section><div class="meta"><span>다시 해보실 시각</span><b>잠시 후</b></div>',
    primaryLabel: '다시 시도하기',
    secondaryLabel: '나중에 하기',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
]
