export default [
  {
    key: 'transfer-home',
    title: '홈',
    description: '잔액과 핵심 서비스만 단순하게 보여줍니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>사용 가능 금액</strong><p>1,240,000원</p></div></section><div class="choices"><div class="choice active"><span>송금하기</span><i>✓</i></div><div class="choice "><span>고지서 확인</span><i></i></div></div><div class="note"><b>안내</b><span>최근 수취인 바로가기는 제외했습니다.</span></div>',
    primaryLabel: '음성으로 송금',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-listening',
    title: '듣는 중',
    description: '사용자의 송금 요청을 듣습니다.',
    contentHtml:
      '<div class="voice"><span class="glow g1"></span><span class="glow g2"></span><div class="mic-wrap"><span class="pulse p1"></span><span class="pulse p2"></span><span class="mic"><span class="mic-body"></span><span class="mic-stem"></span></span></div><div class="wave"><i style="height:12px"></i><i style="height:20px"></i><i style="height:32px"></i><i style="height:46px"></i><i style="height:28px"></i><i style="height:54px"></i><i style="height:64px"></i><i style="height:42px"></i><i style="height:58px"></i><i style="height:36px"></i><i style="height:50px"></i><i style="height:24px"></i><i style="height:38px"></i><i style="height:18px"></i><i style="height:12px"></i></div><p class="vstat"><span class="live"></span>듣고 있어요</p></div><div class="stt"><div class="stt-head"><span class="stt-dot"></span>인식하고 있어요</div><p class="stt-text">김영희에게 오만원<span class="stt-caret"></span></p></div><section class="hero "><div class="hero-icon">✓</div><div><strong>말씀해 주세요</strong><p>“김영희에게 오만원 보내줘”</p></div></section>',
    primaryLabel: '',
    secondaryLabel: '키보드로 입력',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-processing',
    title: '처리 중',
    description: '인식한 내용을 안전하게 분석합니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>요청을 확인하고 있어요</strong><p>잠시만 기다려 주세요.</p></div></section><div class="steps"><i class="on"></i><i class="on"></i><i class=""></i></div>',
    primaryLabel: '',
    secondaryLabel: '취소',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-speaking',
    title: '읽어드리는 중',
    description: '결과를 말하는 도중에도 새 명령을 받을 수 있습니다.',
    contentHtml:
      '<div class="voice"><span class="glow g1"></span><span class="glow g2"></span><div class="mic-wrap"><span class="pulse p1"></span><span class="pulse p2"></span><span class="mic"><span class="mic-body"></span><span class="mic-stem"></span></span></div><div class="wave"><i style="height:12px"></i><i style="height:20px"></i><i style="height:32px"></i><i style="height:46px"></i><i style="height:28px"></i><i style="height:54px"></i><i style="height:64px"></i><i style="height:42px"></i><i style="height:58px"></i><i style="height:36px"></i><i style="height:50px"></i><i style="height:24px"></i><i style="height:38px"></i><i style="height:18px"></i><i style="height:12px"></i></div><p class="vstat"><span class="live"></span>읽어드리는 중</p></div><div class="stt done"><div class="stt-head"><span class="stt-dot"></span>이렇게 들었어요</div><p class="stt-text">김영희에게 오만원 보내줘</p></div><section class="hero "><div class="hero-icon">✓</div><div><strong>제가 이해한 내용을 읽을게요</strong><p>말씀하시면 바로 멈추고 다시 들을게요.</p></div></section>',
    primaryLabel: '다시 말하기',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-recipient-select',
    title: '받는 분 선택',
    description: '동명이인 후보를 명확히 구분합니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>김영희 · 신한 1234</span><i>✓</i></div><div class="choice "><span>김영희 · 국민 7701</span><i></i></div></div>',
    primaryLabel: '이 사람에게 보내기',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-contacts-permission',
    title: '연락처 권한 없음',
    description: '거부 시에도 직접 검색할 수 있습니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>연락처를 불러올 수 없어요</strong><p>설정에서 허용하거나 직접 찾을 수 있습니다.</p></div></section><div class="field "><span>이름 또는 계좌번호 검색</span><b>›</b></div>',
    primaryLabel: '직접 찾기',
    secondaryLabel: '설정 열기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-amount-confirm',
    title: '금액 재확인',
    description: '보낼 금액을 입력하고 한 번 더 확인합니다.',
    contentHtml:
      '<div class="amount"><small>확인할 금액</small><strong>입력한 금액을 확인해 주세요</strong></div>',
    primaryLabel: '이 금액이 맞아요',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-confirm',
    title: '최종 확인',
    description: '수취인·금액·계좌를 충분히 확인합니다.',
    contentHtml:
      '<div class="meta"><span>받는 분</span><strong>김영희</strong></div><div class="meta"><span>금액</span><strong>50,000원</strong></div><div class="meta"><span>출금 계좌</span><strong>신한 · 1234</strong></div><section class="hero "><div class="hero-icon">✓</div><div><strong>최소 20초 확인</strong><p>정보를 읽고 들은 뒤 직접 진행합니다.</p></div></section>',
    primaryLabel: '확인 후 보내기',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-risk-confirm',
    title: '위험 확인 질문',
    description: '위험 신호가 있으면 추가 질문을 보여줍니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">?</div><div><strong>조금 더 확인할게요</strong><p>누군가 전화를 끊지 말라고 했나요?</p></div></section><div class="choices"><div class="choice active"><span>아니요</span><i>✓</i></div><div class="choice "><span>잘 모르겠어요</span><i></i></div></div>',
    primaryLabel: '답변 제출',
    secondaryLabel: '',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-pending',
    title: '송금 보류',
    description: '위험도가 높으면 즉시 실행하지 않습니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>송금을 잠시 보류했어요</strong><p>등록된 보호자에게 확인 요청을 보냈습니다.</p></div></section>',
    primaryLabel: '',
    secondaryLabel: '홈으로',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-guardian-confirm',
    title: '보호자 확인',
    description: '서버 정책에 따른 인증값을 입력합니다.',
    contentHtml:
      '<div class="field "><span>인증값 입력</span><b>›</b></div><div class="note"><b>안내</b><span>자릿수·유효시간·재시도 횟수는 화면에 임의로 고정하지 않습니다.</span></div>',
    primaryLabel: '확인 요청',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-guardian-message-failed',
    title: '보호자 메시지 실패',
    description: 'MMS 전송에 실패한 경우 재시도 경로를 줍니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>확인 메시지를 보내지 못했어요</strong><p>네트워크 상태를 확인해 주세요.</p></div></section>',
    primaryLabel: '다시 보내기',
    secondaryLabel: '송금 취소',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-authentication-expired',
    title: '인증 불일치·만료',
    description: '잘못된 값과 만료 상태를 명확히 구분합니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>인증을 완료할 수 없어요</strong><p>입력값이 다르거나 유효시간이 지났습니다.</p></div></section>',
    primaryLabel: '새 인증 요청',
    secondaryLabel: '취소',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-complete',
    title: '송금 완료',
    description: '핵심 실행 결과만 보여줍니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>송금이 완료됐어요</strong><p>김영희님에게 50,000원</p></div></section><div class="meta"><span>처리 시각</span><strong>오후 2:31</strong></div><div class="meta"><span>상태</span><strong>완료</strong></div><div class="note"><b>안내</b><span>영수증 보기와 즉시 잔액 표시는 제외했습니다.</span></div>',
    primaryLabel: '확인',
    secondaryLabel: '',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-voice-recognition-failed',
    title: '음성 인식 실패',
    description: '음성이 어렵다면 텍스트 입력으로 전환합니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>말씀을 정확히 듣지 못했어요</strong><p>조용한 곳에서 다시 말하거나 직접 입력해 주세요.</p></div></section>',
    primaryLabel: '다시 말하기',
    secondaryLabel: '직접 입력',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-recipient-not-found',
    title: '그런 분이 없어요',
    description: '수취인을 찾지 못했습니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>“김영희” 님을 못 찾았어요</strong><p>이름을 다시 말씀해 주시겠어요?</p></div></section><div class="stt done"><div class="stt-head"><span class="stt-dot"></span>이렇게 들었어요</div><p class="stt-text">김영희</p></div>',
    primaryLabel: '다시 말하기',
    secondaryLabel: '계좌번호로 보내기',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-recipient-confirm',
    title: '이분이 맞나요',
    description: '비슷한 이름이 여러 명 있습니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">?</div><div><strong>닮은 이름이 두 분 있어요</strong><p>받으실 분을 골라주세요.</p></div></section><div class="choices"><div class="choice active"><span>김영희 · 자녀</span><i>✓</i></div><div class="choice "><span>김영회 · 지인</span><i></i></div></div><div class="note"><b>안내</b><span>헷갈리시면 그만두셔도 괜찮아요.</span></div>',
    primaryLabel: '이분께 보내기',
    secondaryLabel: '그만두기',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-account-select',
    title: '어느 계좌에서',
    description: '돈이 나갈 계좌를 고릅니다.',
    contentHtml:
      '<div class="choices"><div class="choice active"><span>국민 ****-3391</span><i>✓</i></div><div class="choice "><span>신한 ****-1234</span><i></i></div></div><div class="meta"><span>국민 잔액</span><b>1,240,500원</b></div><div class="meta"><span>신한 잔액</span><b>318,000원</b></div><div class="note"><b>안내</b><span>잔액이 넉넉한 계좌를 먼저 보여드려요.</span></div>',
    primaryLabel: '이 계좌로 보내기',
    secondaryLabel: '뒤로',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-existing-plan',
    title: '하시던 송금이 있어요',
    description: '중단된 송금을 이어서 진행합니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">!</div><div><strong>마무리하지 못한 송금이 있어요</strong><p>10분 전에 여기까지 하셨어요.</p></div></section><div class="meta"><span>받는 분</span><b>김영희 · 자녀</b></div><div class="amount"><small>보내려던 금액</small><strong>50,000원</strong></div>',
    primaryLabel: '이어서 보내기',
    secondaryLabel: '없던 일로 하기',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-not-sent',
    title: '보내지 않았어요',
    description: '요청하신 대로 송금을 멈췄습니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>돈이 나가지 않았어요</strong><p>계좌에서 빠져나간 금액이 없어요.</p></div></section><div class="amount"><small>그대로 있는 잔액</small><strong>1,240,500원</strong></div>',
    primaryLabel: '홈으로',
    secondaryLabel: '다시 송금하기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-expired',
    title: '시간이 지났어요',
    description: '확인 시간이 지나 거래를 닫았습니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">!</div><div><strong>3분이 지나 취소했어요</strong><p>안전을 위해 오래 두지 않아요.</p></div></section><div class="note"><b>안내</b><span>돈은 나가지 않았어요. 다시 하시면 돼요.</span></div>',
    primaryLabel: '처음부터 다시',
    secondaryLabel: '홈으로',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-executing',
    title: '보내는 중',
    description: '지금 송금을 실행하고 있습니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>은행에 보내고 있어요</strong><p>잠시만 기다려 주세요.</p></div></section><div class="steps"><i class="on"></i><i class="on"></i><i class=""></i></div><div class="amount"><small>보내는 금액</small><strong>50,000원</strong></div>',
    primaryLabel: '',
    secondaryLabel: '기다리는 중…',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-failed',
    title: '보내지 못했어요',
    description: '송금이 실패했습니다.',
    contentHtml:
      '<section class="hero danger"><div class="hero-icon">!</div><div><strong>은행에서 처리하지 못했어요</strong><p>돈은 그대로 있으니 안심하세요.</p></div></section><div class="meta"><span>실패한 시각</span><b>오후 2:14</b></div><div class="amount"><small>그대로 있는 잔액</small><strong>1,240,500원</strong></div>',
    primaryLabel: '다시 시도하기',
    secondaryLabel: '그만두기',
    variant: 'destructive',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-replay',
    title: '다시 들려드릴게요',
    description: '방금 안내를 처음부터 읽어드립니다.',
    contentHtml:
      '<div class="voice"><span class="glow g1"></span><span class="glow g2"></span><div class="mic-wrap"><span class="pulse p1"></span><span class="pulse p2"></span><span class="mic"><span class="mic-body"></span><span class="mic-stem"></span></span></div><div class="wave"><i style="height:12px"></i><i style="height:20px"></i><i style="height:32px"></i><i style="height:46px"></i><i style="height:28px"></i><i style="height:54px"></i><i style="height:64px"></i><i style="height:42px"></i><i style="height:58px"></i><i style="height:36px"></i><i style="height:50px"></i><i style="height:24px"></i><i style="height:38px"></i><i style="height:18px"></i><i style="height:12px"></i></div><p class="vstat"><span class="live"></span>읽어드리는 중</p></div><div class="stt done"><div class="stt-head"><span class="stt-dot"></span>읽고 있는 내용</div><p class="stt-text">김영희 님께 오만원을 보냅니다</p></div>',
    primaryLabel: '다시 듣기',
    secondaryLabel: '그만 듣기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-misheard',
    title: '잘못 들었나요',
    description: '틀린 부분만 고쳐서 다시 확인합니다.',
    contentHtml:
      '<div class="stt done"><div class="stt-head"><span class="stt-dot"></span>제가 들은 말</div><p class="stt-text">김영희에게 오만원</p></div><div class="choices"><div class="choice active"><span>이름 고치기</span><i>✓</i></div><div class="choice "><span>금액 고치기</span><i></i></div></div><div class="note"><b>안내</b><span>고칠 곳만 말씀하셔도 돼요.</span></div>',
    primaryLabel: '고쳐서 말하기',
    secondaryLabel: '처음부터 다시',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-conversation-ended',
    title: '음성 대화 끝',
    description: '음성 안내를 마쳤습니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>말로 하는 안내를 껐어요</strong><p>이제 화면 단추로 계속하시면 돼요.</p></div></section><div class="note"><b>안내</b><span>마이크 단추를 누르면 다시 켜져요.</span></div>',
    primaryLabel: '화면으로 계속하기',
    secondaryLabel: '음성 다시 켜기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-scheduled-list',
    title: '이번 달 보낼 돈',
    description: '미리 정해두신 송금을 날짜순으로 보여줍니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>세 건이 남았어요</strong><p>이미 보낸 것은 아래에 따로 모아뒀어요.</p></div></section><div class="field"><span>월세 · 매달 25일</span><b>400,000원</b></div><div class="field"><span>손주 용돈 · 매달 10일</span><b>100,000원</b></div><div class="field"><span>보험료 · 매달 28일</span><b>85,000원</b></div><div class="note"><b>안내</b><span>정한 날에 알려만 드려요. 저절로 빠져나가지 않아요.</span></div>',
    primaryLabel: '보낼 돈 추가하기',
    secondaryLabel: '보낸 내역 보기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-scheduled-create',
    title: '보낼 돈 정하기',
    description: '누구에게 언제 보낼지 미리 적어둡니다.',
    contentHtml:
      '<div class="field focus"><span>받는 분</span><b>김영희 · 자녀</b></div><div class="field"><span>보낼 금액</span><b>400,000원</b></div><div class="field"><span>보낼 날짜</span><b>매달 25일</b></div><div class="choices"><div class="choice active"><span>매달 반복</span><i>✓</i></div><div class="choice "><span>한 번만</span><i></i></div></div><div class="note"><b>안내</b><span>정한 날 아침에 알려드려요.</span></div>',
    primaryLabel: '저장하기',
    secondaryLabel: '취소',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-scheduled-due',
    title: '오늘 보내실 것이 있어요',
    description: '소리 없이 진동으로 먼저 알립니다.',
    contentHtml:
      '<section class="hero "><div class="hero-icon">✓</div><div><strong>월세 보내는 날이에요</strong><p>눌러서 들으시면 자세히 알려드려요.</p></div></section><div class="meta"><span>알림 온 시각</span><b>오늘 아침 9시</b></div><div class="note"><b>안내</b><span>밖에서도 안심하시라고, 금액은 소리로 먼저 말하지 않아요.</span></div>',
    primaryLabel: '들어보기',
    secondaryLabel: '나중에',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-scheduled-complete',
    title: '이미 보내셨어요',
    description: '이번 달 송금이 끝난 것을 확인했습니다.',
    contentHtml:
      '<section class="hero warn"><div class="hero-icon">!</div><div><strong>이달 월세는 벌써 보냈어요</strong><p>지금 또 보내면 두 번 나가요.</p></div></section><div class="meta"><span>보낸 날</span><b>이달 25일 오전</b></div><div class="meta"><span>보낸 금액</span><b>400,000원</b></div><div class="meta"><span>받으신 분</span><b>김영희 · 자녀</b></div>',
    primaryLabel: '그만두기',
    secondaryLabel: '그래도 보내기',
    variant: 'warning',
    showHelp: true,
    showTabs: false,
  },
  {
    key: 'transfer-scheduled-edit',
    title: '보낼 돈 고치기',
    description: '금액과 날짜를 바꾸거나 지웁니다.',
    contentHtml:
      '<div class="field"><span>받는 분</span><b>김영희 · 자녀</b></div><div class="field focus"><span>보낼 금액</span><b>400,000원</b></div><div class="field"><span>보낼 날짜</span><b>매달 25일</b></div><div class="note"><b>안내</b><span>지워도 이미 보낸 돈은 그대로예요.</span></div>',
    primaryLabel: '저장하기',
    secondaryLabel: '이 약속 지우기',
    variant: 'default',
    showHelp: true,
    showTabs: false,
  },
]
